// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using ProjectManagementService.Domain.Entities;
using TaskEntity = ProjectManagementService.Domain.Entities.Task;

namespace ProjectManagementService.Infrastructure.Persistence;

public partial class MyDbContext : DbContext
{
    public MyDbContext(DbContextOptions<MyDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ActivityLog> ActivityLogs { get; set; }

    public virtual DbSet<Attachment> Attachments { get; set; }

    public virtual DbSet<CommentMessage> CommentMessages { get; set; }

    public virtual DbSet<CommentThread> CommentThreads { get; set; }

    public virtual DbSet<FileAsset> FileAssets { get; set; }

    public virtual DbSet<Project> Projects { get; set; }

    public virtual DbSet<ProjectMember> ProjectMembers { get; set; }

    public virtual DbSet<ProjectStatus> ProjectStatuses { get; set; }

    public virtual DbSet<TaskEntity> Tasks { get; set; }

    public virtual DbSet<TaskAssignee> TaskAssignees { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Meeting> Meetings { get; set; }

    public virtual DbSet<Reminder> Reminders { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_unicode_ci")
            .HasCharSet("utf8mb4");


        modelBuilder.Entity<ActivityLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("activity_log")
                .UseCollation("utf8mb4_0900_ai_ci");

            entity.HasIndex(e => e.ActorId, "fk_al_actor");

            entity.HasIndex(e => new { e.EntityType, e.EntityId }, "idx_al_entity");

            entity.HasIndex(e => new { e.ProjectId, e.CreatedAt }, "idx_al_project");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("action");
            entity.Property(e => e.ActorId).HasColumnName("actor_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.EntityId).HasColumnName("entity_id");
            entity.Property(e => e.EntityType)
                .IsRequired()
                .HasColumnType("enum('project','task','comment','file','status')")
                .HasColumnName("entity_type");
            entity.Property(e => e.MetadataJson)
                .HasColumnType("json")
                .HasColumnName("metadata_json");
            entity.Property(e => e.ProjectId).HasColumnName("project_id");

            entity.HasOne(d => d.Actor).WithMany(p => p.ActivityLogs)
                .HasForeignKey(d => d.ActorId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("fk_al_actor");

            entity.HasOne(d => d.Project).WithMany(p => p.ActivityLogs)
                .HasForeignKey(d => d.ProjectId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("fk_al_project");
        });

        modelBuilder.Entity<Attachment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("attachment")
                .UseCollation("utf8mb4_0900_ai_ci");

            entity.HasIndex(e => e.FileId, "fk_att_file");

            entity.HasIndex(e => e.DeletedAt, "idx_att_deleted");

            entity.HasIndex(e => new { e.OwnerType, e.OwnerId }, "idx_att_owner");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.DeletedAt)
                .HasColumnType("datetime")
                .HasColumnName("deleted_at");
            entity.Property(e => e.FileId).HasColumnName("file_id");
            entity.Property(e => e.OwnerId).HasColumnName("owner_id");
            entity.Property(e => e.OwnerType)
                .IsRequired()
                .HasColumnType("enum('project','task','comment')")
                .HasColumnName("owner_type");

            entity.HasOne(d => d.File).WithMany(p => p.Attachments)
                .HasForeignKey(d => d.FileId)
                .HasConstraintName("fk_att_file");
        });

        modelBuilder.Entity<CommentMessage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("comment_message")
                .UseCollation("utf8mb4_0900_ai_ci");

            entity.HasIndex(e => e.CreatedBy, "fk_cm_user");

            entity.HasIndex(e => e.DeletedAt, "idx_cm_deleted");

            entity.HasIndex(e => new { e.ThreadId, e.CreatedAt }, "idx_cm_thread");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Body)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("body");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.DeletedAt)
                .HasColumnType("datetime")
                .HasColumnName("deleted_at");
            entity.Property(e => e.ThreadId).HasColumnName("thread_id");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.CommentMessages)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_cm_user");

            entity.HasOne(d => d.Thread).WithMany(p => p.CommentMessages)
                .HasForeignKey(d => d.ThreadId)
                .HasConstraintName("fk_cm_thread");
        });

        modelBuilder.Entity<CommentThread>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("comment_thread")
                .UseCollation("utf8mb4_0900_ai_ci");

            entity.HasIndex(e => e.CreatedBy, "fk_ct_user");

            entity.HasIndex(e => e.DeletedAt, "idx_ct_deleted");

            entity.HasIndex(e => new { e.ProjectId, e.IsResolved }, "idx_ct_project");

            entity.HasIndex(e => new { e.TargetType, e.TargetId }, "idx_ct_target");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AnchorPayload)
                .IsRequired()
                .HasColumnType("json")
                .HasColumnName("anchor_payload");
            entity.Property(e => e.AnchorType)
                .IsRequired()
                .HasColumnType("enum('text_range','field','attachment','position')")
                .HasColumnName("anchor_type");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.DeletedAt)
                .HasColumnType("datetime")
                .HasColumnName("deleted_at");
            entity.Property(e => e.IsResolved).HasColumnName("is_resolved");
            entity.Property(e => e.ProjectId).HasColumnName("project_id");
            entity.Property(e => e.ResolvedAt)
                .HasColumnType("datetime")
                .HasColumnName("resolved_at");
            entity.Property(e => e.TargetId).HasColumnName("target_id");
            entity.Property(e => e.TargetType)
                .IsRequired()
                .HasColumnType("enum('task','project')")
                .HasColumnName("target_type");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.CommentThreads)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_ct_user");

            entity.HasOne(d => d.Project).WithMany(p => p.CommentThreads)
                .HasForeignKey(d => d.ProjectId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("fk_ct_proj");
        });

        modelBuilder.Entity<FileAsset>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("file_asset")
                .UseCollation("utf8mb4_0900_ai_ci");

            entity.HasIndex(e => e.DeletedAt, "idx_fa_deleted");

            entity.HasIndex(e => e.OwnerUserId, "idx_fa_owner");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ByteSize).HasColumnName("byte_size");
            entity.Property(e => e.Checksum)
                .HasMaxLength(128)
                .HasColumnName("checksum");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.DeletedAt)
                .HasColumnType("datetime")
                .HasColumnName("deleted_at");
            entity.Property(e => e.Height).HasColumnName("height");
            entity.Property(e => e.MetaJson)
                .HasColumnType("json")
                .HasColumnName("meta_json");
            entity.Property(e => e.MimeType)
                .HasMaxLength(150)
                .HasColumnName("mime_type");
            entity.Property(e => e.OwnerUserId).HasColumnName("owner_user_id");
            entity.Property(e => e.S3Key)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("s3_key");
            entity.Property(e => e.Url)
                .IsRequired()
                .HasMaxLength(1000)
                .HasColumnName("url");
            entity.Property(e => e.Width).HasColumnName("width");

            entity.HasOne(d => d.OwnerUser).WithMany(p => p.FileAssets)
                .HasForeignKey(d => d.OwnerUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_fa_owner");
        });

        modelBuilder.Entity<Project>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("project")
                .UseCollation("utf8mb4_0900_ai_ci");

            entity.HasIndex(e => e.DeletedAt, "idx_project_deleted");

            entity.HasIndex(e => e.OwnerId, "idx_project_owner");

            entity.HasIndex(e => e.Status, "idx_project_status");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.DeletedAt)
                .HasColumnType("datetime")
                .HasColumnName("deleted_at");
            entity.Property(e => e.DemoUrl)
                .HasMaxLength(500)
                .HasColumnName("demo_url");
            entity.Property(e => e.Description)
                .HasColumnType("mediumtext")
                .HasColumnName("description");
            entity.Property(e => e.EndDate).HasColumnName("end_date");
            entity.Property(e => e.Highlight)
                .HasMaxLength(500)
                .HasColumnName("highlight");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
            entity.Property(e => e.OwnerId).HasColumnName("owner_id");
            entity.Property(e => e.ShortIntro)
                .HasMaxLength(500)
                .HasColumnName("short_intro");
            entity.Property(e => e.StartDate).HasColumnName("start_date");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValueSql("'active'")
                .HasColumnName("status");
            entity.Property(e => e.UpdatedAt)
                .ValueGeneratedOnAddOrUpdate()
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Owner).WithMany(p => p.Projects)
                .HasForeignKey(d => d.OwnerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_project_owner");
        });

        modelBuilder.Entity<ProjectMember>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("project_member")
                .UseCollation("utf8mb4_0900_ai_ci");

            entity.HasIndex(e => e.UserId, "fk_pm_user");

            entity.HasIndex(e => e.DeletedAt, "idx_pm_deleted");

            entity.HasIndex(e => new { e.ProjectId, e.UserId }, "uk_proj_user").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.DeletedAt)
                .HasColumnType("datetime")
                .HasColumnName("deleted_at");
            entity.Property(e => e.ProjectId).HasColumnName("project_id");
            entity.Property(e => e.Role)
                .HasDefaultValueSql("'editor'")
                .HasColumnType("enum('owner','admin','editor','viewer')")
                .HasColumnName("role");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Project).WithMany(p => p.ProjectMembers)
                .HasForeignKey(d => d.ProjectId)
                .HasConstraintName("fk_pm_proj");

            entity.HasOne(d => d.User).WithMany(p => p.ProjectMembers)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("fk_pm_user");
        });

        modelBuilder.Entity<ProjectStatus>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("project_status")
                .UseCollation("utf8mb4_0900_ai_ci");

            entity.HasIndex(e => e.DeletedAt, "idx_ps_deleted");

            entity.HasIndex(e => new { e.ProjectId, e.OrderIndex }, "idx_ps_order");

            entity.HasIndex(e => new { e.ProjectId, e.Slug }, "uk_proj_slug").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Color)
                .HasMaxLength(20)
                .HasColumnName("color");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.DeletedAt)
                .HasColumnType("datetime")
                .HasColumnName("deleted_at");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.OrderIndex).HasColumnName("order_index");
            entity.Property(e => e.ProjectId).HasColumnName("project_id");
            entity.Property(e => e.Slug)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("slug");
            entity.Property(e => e.UpdatedAt)
                .ValueGeneratedOnAddOrUpdate()
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Project).WithMany(p => p.ProjectStatuses)
                .HasForeignKey(d => d.ProjectId)
                .HasConstraintName("fk_ps_proj");
        });

        modelBuilder.Entity<TaskEntity>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("task")
                .UseCollation("utf8mb4_0900_ai_ci");

            entity.HasIndex(e => e.CreatedBy, "fk_task_creator");

            entity.HasIndex(e => new { e.Title, e.Description }, "ft_task_text").HasAnnotation("MySql:FullTextIndex", true);

            entity.HasIndex(e => e.DeletedAt, "idx_task_deleted");

            entity.HasIndex(e => e.DueDate, "idx_task_due");

            entity.HasIndex(e => e.ProjectId, "idx_task_proj");

            entity.HasIndex(e => new { e.StatusId, e.OrderIndex }, "idx_task_status");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.DeletedAt)
                .HasColumnType("datetime")
                .HasColumnName("deleted_at");
            entity.Property(e => e.Description)
                .HasColumnType("mediumtext")
                .HasColumnName("description");
            entity.Property(e => e.DueDate).HasColumnName("due_date");
            entity.Property(e => e.OrderIndex).HasColumnName("order_index");
            entity.Property(e => e.Priority)
                .HasDefaultValueSql("'medium'")
                .HasColumnType("enum('low','medium','high','emergency')")
                .HasColumnName("priority");
            entity.Property(e => e.ProjectId).HasColumnName("project_id");
            entity.Property(e => e.StatusId).HasColumnName("status_id");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasColumnName("title");
            entity.Property(e => e.UpdatedAt)
                .ValueGeneratedOnAddOrUpdate()
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.Tasks)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_task_creator");

            entity.HasOne(d => d.Project).WithMany(p => p.Tasks)
                .HasForeignKey(d => d.ProjectId)
                .HasConstraintName("fk_task_proj");

            entity.HasOne(d => d.Status).WithMany(p => p.Tasks)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("fk_task_status");
        });

        modelBuilder.Entity<TaskAssignee>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("task_assignee")
                .UseCollation("utf8mb4_0900_ai_ci");

            entity.HasIndex(e => e.UserId, "fk_ta_user");

            entity.HasIndex(e => e.DeletedAt, "idx_ta_deleted");

            entity.HasIndex(e => new { e.TaskId, e.UserId }, "uk_task_user").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.DeletedAt)
                .HasColumnType("datetime")
                .HasColumnName("deleted_at");
            entity.Property(e => e.TaskId).HasColumnName("task_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Task).WithMany(p => p.TaskAssignees)
                .HasForeignKey(d => d.TaskId)
                .HasConstraintName("fk_ta_task");

            entity.HasOne(d => d.User).WithMany(p => p.TaskAssignees)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("fk_ta_user");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity
                .ToTable("user")
                .UseCollation("utf8mb4_0900_ai_ci");

            entity.HasIndex(e => e.Email, "email").IsUnique();

            entity.HasIndex(e => e.DeletedAt, "idx_user_deleted");

            entity.HasIndex(e => e.Username, "username").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Address)
                .HasMaxLength(255)
                .HasColumnName("address");
            entity.Property(e => e.AvatarUrl)
                .HasMaxLength(500)
                .HasColumnName("avatar_url");
            entity.Property(e => e.Bio)
                .HasColumnType("text")
                .HasColumnName("bio");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.DeletedAt)
                .HasColumnType("datetime")
                .HasColumnName("deleted_at");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasColumnName("email");
            entity.Property(e => e.FullName)
                .HasMaxLength(255)
                .HasColumnName("full_name");
            entity.Property(e => e.Gender)
                .HasColumnType("enum('male','female','other')")
                .HasColumnName("gender");
            entity.Property(e => e.LastLoginAt)
                .HasColumnType("datetime")
                .HasColumnName("last_login_at");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("password_hash");
            entity.Property(e => e.Phone)
                .HasMaxLength(50)
                .HasColumnName("phone");
            entity.Property(e => e.SettingsJson)
                .HasColumnType("json")
                .HasColumnName("settings_json");
            entity.Property(e => e.SocialLinksJson)
                .HasColumnType("json")
                .HasColumnName("social_links_json");
            entity.Property(e => e.UpdatedAt)
                .ValueGeneratedOnAddOrUpdate()
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            entity.Property(e => e.Username)
                .HasMaxLength(100)
                .HasColumnName("username");
        });

        modelBuilder.Entity<Meeting>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("meeting");

            entity.HasIndex(e => new { e.UserId, e.StartTime }, "idx_meeting_user");

            entity.HasIndex(e => e.DeletedAt, "idx_meeting_deleted");

            entity.HasIndex(e => new { e.StartTime, e.EndTime }, "idx_meeting_time");

            entity.Property(e => e.Id).HasColumnName("id");
            
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("title");
            
            entity.Property(e => e.Description)
                .HasColumnType("text")
                .HasColumnName("description");
            
            entity.Property(e => e.StartTime)
                .HasColumnType("datetime")
                .HasColumnName("start_time");
            
            entity.Property(e => e.EndTime)
                .HasColumnType("datetime")
                .HasColumnName("end_time");
            
            entity.Property(e => e.MeetingLink)
                .HasMaxLength(500)
                .HasColumnName("meeting_link");
            
            entity.Property(e => e.UserId)
                .HasColumnName("user_id");
            
            entity.Property(e => e.Attendees)
                .HasColumnType("json")
                .HasColumnName("attendees");
            
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            
            entity.Property(e => e.UpdatedAt)
                .ValueGeneratedOnAddOrUpdate()
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("updated_at");
            
            entity.Property(e => e.DeletedAt)
                .HasColumnType("datetime")
                .HasColumnName("deleted_at");

            entity.HasOne(d => d.User).WithMany(p => p.Meetings)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("fk_meeting_user");
        });

        modelBuilder.Entity<Reminder>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("reminders");

            entity.HasIndex(e => e.UserId, "idx_reminders_userid");
            entity.HasIndex(e => e.ReminderTime, "idx_reminders_remindertime");
            entity.HasIndex(e => e.IsEmailSent, "idx_reminders_emailsent");
            entity.HasIndex(e => e.IsExpired, "idx_reminders_expired");

            entity.Property(e => e.Id)
                .HasMaxLength(36)
                .HasColumnName("Id");

            entity.Property(e => e.UserId)
                .HasColumnName("UserId");

            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("Title");

            entity.Property(e => e.Note)
                .HasColumnType("text")
                .HasColumnName("Note");

            entity.Property(e => e.ReminderTime)
                .HasColumnType("datetime")
                .HasColumnName("ReminderTime");

            entity.Property(e => e.IsEmailSent)
                .HasColumnName("IsEmailSent");

            entity.Property(e => e.EmailSentAt)
                .HasColumnType("datetime")
                .HasColumnName("EmailSentAt");

            entity.Property(e => e.IsExpired)
                .HasColumnName("IsExpired");

            entity.Property(e => e.IsCompleted)
                .HasColumnName("IsCompleted");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("datetime")
                .HasColumnName("CreatedAt");

            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("UpdatedAt");

            entity.HasOne(d => d.User).WithMany()
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("fk_reminders_user");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}