// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectManagementService.Domain.Entities;

public partial class ActivityLog
{
    public long Id { get; set; }

    public long? ActorId { get; set; }

    public string Action { get; set; }

    public string EntityType { get; set; }

    public long EntityId { get; set; }

    public long? ProjectId { get; set; }

    public string MetadataJson { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User Actor { get; set; }

    public virtual Project Project { get; set; }
}