// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectManagementService.Domain.Entities;

public partial class Attachment
{
    public long Id { get; set; }

    public long FileId { get; set; }

    public string OwnerType { get; set; }

    public long OwnerId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual FileAsset File { get; set; }
}