// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectManagementService.Domain.Entities;

public partial class CommentThread
{
    public long Id { get; set; }

    public long? ProjectId { get; set; }

    public string TargetType { get; set; }

    public long TargetId { get; set; }

    public string AnchorType { get; set; }

    public string AnchorPayload { get; set; }

    public bool IsResolved { get; set; }

    public long CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ResolvedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<CommentMessage> CommentMessages { get; set; } = new List<CommentMessage>();

    public virtual User CreatedByNavigation { get; set; }

    public virtual Project Project { get; set; }
}