// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectManagementService.Domain.Entities;

public partial class CommentMessage
{
    public long Id { get; set; }

    public long ThreadId { get; set; }

    public string Body { get; set; }

    public long CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual CommentThread Thread { get; set; }
}