// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectManagementService.Domain.Entities;

public partial class FileAsset
{
    public long Id { get; set; }

    public long OwnerUserId { get; set; }

    public string S3Key { get; set; }

    public string Url { get; set; }

    public string MimeType { get; set; }

    public long? ByteSize { get; set; }

    public int? Width { get; set; }

    public int? Height { get; set; }

    public string Checksum { get; set; }

    public string MetaJson { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<Attachment> Attachments { get; set; } = new List<Attachment>();

    public virtual User OwnerUser { get; set; }
}