// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectManagementService.Domain.Entities;

public partial class ProjectStatus
{
    public long Id { get; set; }

    public long ProjectId { get; set; }

    public string Name { get; set; }

    public string Slug { get; set; }

    public string Color { get; set; }

    public int OrderIndex { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual Project Project { get; set; }

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();
}