// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectManagementService.Domain.Entities;

public partial class User
{
    public long Id { get; set; }

    public string Email { get; set; }

    public string Username { get; set; }

    public string PasswordHash { get; set; }

    public string FullName { get; set; }

    public string Gender { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public string Bio { get; set; }

    public string SocialLinksJson { get; set; }

    public string AvatarUrl { get; set; }

    public string SettingsJson { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime? LastLoginAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<ActivityLog> ActivityLogs { get; set; } = new List<ActivityLog>();

    public virtual ICollection<CommentMessage> CommentMessages { get; set; } = new List<CommentMessage>();

    public virtual ICollection<CommentThread> CommentThreads { get; set; } = new List<CommentThread>();

    public virtual ICollection<FileAsset> FileAssets { get; set; } = new List<FileAsset>();

    public virtual ICollection<ProjectMember> ProjectMembers { get; set; } = new List<ProjectMember>();

    public virtual ICollection<Project> Projects { get; set; } = new List<Project>();

    public virtual ICollection<TaskAssignee> TaskAssignees { get; set; } = new List<TaskAssignee>();

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();

    public virtual ICollection<Meeting> Meetings { get; set; } = new List<Meeting>();
}